/**
 * Footage the band has supplied. Empty slots render nothing, on the same
 * pattern as `contact.ts` and `content.ts`.
 *
 * `drum-major` is trimmed from the band's own parade footage, 14.0s to 24.0s
 * of a two minute clip, chosen because the camera is locked and the framing at
 * the two ends is near identical, so the loop point is nearly invisible. It is
 * re-encoded muted at 1.1 Mbps, which is the ceiling worth spending on a 576 by
 * 1024 source. The source is a TikTok copy carrying the band's own watermark,
 * so it is already a generation down from the camera original; re-encoding from
 * a true original would look better if one is ever recovered.
 *
 * Committed as a build artifact rather than generated by `npm run images`,
 * which only knows about stills.
 */
export type VideoLoop = {
  /** Base filename in public/assets/video, without extension. */
  name: string;
  /** Describes the footage for anyone who cannot see it play. */
  description: string;
};

export const paradeLoop: VideoLoop | null = {
  name: 'drum-major-loop',
  description:
    'The drum major of the Lagos Musical Band conducting on a Lagos parade ground, the drumline and horns ranked behind him.',
};
