/**
 * Footage the band has supplied, one clip per arm of the band. Empty slots
 * render nothing, on the same pattern as `contact.ts` and `content.ts`.
 *
 * Both are trimmed from the band's own TikTok uploads and carry the band's
 * watermark. They are a generation down from the camera originals, so
 * re-cutting from true originals would look and sound better if any are
 * recovered. 576 by 1024 is the source resolution, not a choice.
 *
 * Segments were chosen for an uncut run with steady framing:
 *   brigade  14.0s to 24.0s of a 121s parade clip. The camera is locked and
 *            the framing at the two ends nearly matches, so the loop barely
 *            reads. Audio is 128 kbps.
 *   choir    64.0s to 72.0s of a 110s hall clip, its longest uncut run. That
 *            clip is a fast-cut edit, so a longer window is not available
 *            without cutting mid-shot. Its source audio is 32 kbps HE-AAC,
 *            which is telephone grade and cannot be improved by re-encoding.
 *
 * Committed as build artifacts rather than generated by `npm run images`,
 * which only knows about stills.
 */
export type BandVideo = {
  /** Base filename in public/assets/video, without extension. */
  name: string;
  /** Describes the footage for anyone who cannot see it play. */
  description: string;
};

export const brigadeVideo: BandVideo | null = {
  name: 'brigade-loop',
  description:
    'The drum major of the Lagos Musical Band conducting on a Lagos parade ground, the drumline and horns ranked behind him.',
};

export const choirVideo: BandVideo | null = {
  name: 'choir-loop',
  description: 'Singers of the Lagos Musical Band standing in ranks in a hall, mid-performance.',
};
